# Generated by Django 4.1 on 2023-11-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_favorites_options_alter_history_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='favorites',
        ),
        migrations.AddField(
            model_name='favorites',
            name='history_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.history', verbose_name='历史记录'),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='图片url'),
        ),
    ]
