# Generated by Django 4.1 on 2023-11-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='配料id')),
                ('chinese_name', models.CharField(max_length=255, unique=True, verbose_name='中文名')),
                ('english_name', models.CharField(max_length=255, unique=True, verbose_name='英文名')),
                ('introduction', models.TextField(verbose_name='简介')),
                ('effects', models.TextField(verbose_name='功效')),
                ('rating', models.FloatField(verbose_name='评分')),
                ('potential_risk_people', models.CharField(max_length=255, null=True, verbose_name='潜在风险人群')),
                ('daily_intake_recommendation', models.TextField(verbose_name='每日建议摄入量')),
            ],
        ),
    ]
