# Generated by Django 4.1 on 2023-11-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': '配料表'},
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='Ingredient',
        ),
    ]
